### ISSUE TITLE
Migrate to python3

### ISSUE THREAD

**Issue by oleksmarkh** [oleksmarkh/music-cluster#6]
Python2 EOL is 01.01.2020 https://www.python.org/doc/sunset-python-2/ and [`mutagen`](https://github.com/quodlibet/mutagen) supports python3.

**Comment by augustozanellato** [comment]
Specifically which version(s) of Python do you need to support?
E.g. are f-strings ok?

**Comment by oleksmarkh** [comment]
@augustozanellato, I'll target the latest that works fine with `mutagen` (hope it's v3.7). Also planning to use f-strings, yes.

**Comment by augustozanellato** [comment]
Fine, I could help with the migration!

**Comment by oleksmarkh** [comment]
I didn't touch this small project for 4 years already, so it's going to be a fun exercise for me :) But thanks, I'll reach out if I stuck!

**Comment by oleksmarkh** [comment]
#7

**Comment by oleksmarkh** [comment]
solved by #7
